# Generated by Django 4.0 on 2021-12-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstnm', models.CharField(max_length=10)),
                ('lastnm', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('pwd', models.CharField(max_length=8)),
                ('cpwd', models.CharField(max_length=8)),
                ('contact', models.IntegerField()),
            ],
        ),
    ]
