# Generated by Django 4.0 on 2021-12-15 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Huser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='register',
            table='Register',
        ),
    ]
