# Generated by Django 4.0 on 2021-12-15 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Huser', '0003_alter_register_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='register',
            table='Register',
        ),
    ]
