# Generated by Django 4.0 on 2021-12-15 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Huser', '0004_alter_register_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
