# Generated by Django 3.2.3 on 2021-12-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pimage',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
