# Generated by Django 4.0.5 on 2022-06-16 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=20)),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm', models.CharField(max_length=100)),
                ('img', models.FileField(upload_to='')),
                ('price', models.IntegerField()),
                ('address', models.TextField()),
                ('area1_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hadmin.area')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unm', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('pwd', models.CharField(max_length=8)),
                ('cpwd', models.CharField(max_length=8)),
                ('add', models.TextField()),
                ('contact', models.IntegerField()),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hadmin.area')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('detail_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Hadmin.detail')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hadmin.user')),
            ],
        ),
        migrations.CreateModel(
            name='Gallary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=20)),
                ('detail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hadmin.detail')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('msg', models.TextField()),
                ('detail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hadmin.detail')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hadmin.user')),
            ],
        ),
        migrations.CreateModel(
            name='contact1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('email2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hadmin.user')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('detail2_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Hadmin.detail')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hadmin.user')),
            ],
        ),
    ]
