# Generated by Django 4.0 on 2021-12-14 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hadmin', '0002_gallary_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallary',
            name='detail_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='Hadmin.detail'),
            preserve_default=False,
        ),
    ]
