# Generated by Django 4.0 on 2021-12-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hadmin', '0003_gallary_detail_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallary',
            name='name',
            field=models.CharField(default=-1, max_length=20),
            preserve_default=False,
        ),
    ]
