# Generated by Django 4.0 on 2021-12-21 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hadmin', '0004_gallary_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('search', models.CharField(max_length=20)),
                ('area2_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hadmin.area')),
                ('detail2_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hadmin.detail')),
            ],
        ),
    ]
