# Generated by Django 4.0 on 2021-12-21 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hadmin', '0005_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='area2_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='search',
        ),
        migrations.AddField(
            model_name='booking',
            name='user_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='Hadmin.user'),
            preserve_default=False,
        ),
    ]
