# Generated by Django 4.0 on 2021-12-21 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hadmin', '0006_remove_booking_area2_id_remove_booking_search_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='detail2_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Hadmin.detail'),
        ),
    ]
