# Generated by Django 4.0 on 2021-12-22 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hadmin', '0007_alter_booking_detail2_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='detail2_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='Hadmin.detail'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('detail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hadmin.detail')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hadmin.user')),
            ],
        ),
    ]
