# Generated by Django 4.0 on 2021-12-29 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hadmin', '0010_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='detail2_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Hadmin.detail'),
        ),
    ]
