# Generated by Django 4.0 on 2021-12-29 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hadmin', '0011_alter_booking_detail2_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('contacts', models.IntegerField()),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('email2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hadmin.user')),
            ],
        ),
        migrations.DeleteModel(
            name='contact',
        ),
    ]
