# Generated by Django 4.0 on 2021-12-29 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hadmin', '0013_alter_booking_detail2_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact1',
            name='name',
        ),
    ]
