# Generated by Django 4.0 on 2021-12-30 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hadmin', '0016_alter_booking_detail2_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='detail2_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Hadmin.detail'),
        ),
    ]
