# Generated by Django 4.0 on 2021-12-30 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hadmin', '0017_alter_booking_detail2_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('detail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hadmin.detail')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hadmin.user')),
            ],
        ),
    ]
