# Generated by Django 4.0 on 2021-12-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hadmin', '0018_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='msg',
            field=models.TextField(default=-1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact1',
            name='contacts',
            field=models.IntegerField(null=True),
        ),
    ]
