# Generated by Django 4.0 on 2021-12-30 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hadmin', '0019_feedback_msg_alter_contact1_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact1',
            name='contacts',
        ),
    ]
