# Generated by Django 3.2.3 on 2022-01-05 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hadmin', '0021_remove_user_area_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='area_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Hadmin.area'),
            preserve_default=False,
        ),
    ]
