# Generated by Django 3.2.3 on 2021-12-27 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_gallary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallary',
            name='bid',
        ),
        migrations.RemoveField(
            model_name='gallary',
            name='name',
        ),
        migrations.AddField(
            model_name='gallary',
            name='pid',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='user.product'),
            preserve_default=False,
        ),
    ]
