# Generated by Django 3.2.3 on 2021-12-29 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20211227_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_item',
            name='startdate',
        ),
    ]
