# Generated by Django 3.2.3 on 2021-12-30 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_order_item_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_item',
            name='billing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.billing'),
        ),
    ]
