# Generated by Django 3.2.3 on 2021-11-17 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
