# Generated by Django 3.2.3 on 2021-12-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
