# Generated by Django 3.2.3 on 2021-12-02 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_blog_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='quantity',
        ),
        migrations.CreateModel(
            name='orderitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.blog')),
            ],
        ),
    ]
